// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp2;

#nullable disable

namespace WinFormsApp2.Migrations
{
    [DbContext(typeof(ExchangeStock))]
    [Migration("20240402140104_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("WinFormsApp2.CurrencyDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disclaimer")
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CurrencyDB");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Timestamp = 1631539200L
                        },
                        new
                        {
                            Id = 2,
                            Timestamp = 1631539200L
                        },
                        new
                        {
                            Id = 3,
                            Timestamp = 1631539200L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
